spring:
  application:
    name: service-consumer

server:
  port: 8082

eureka:
  instance:
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
    # Heartbeat interval in seconds, client sends heartbeat to server every 2 seconds
    lease-renewal-interval-in-seconds: 2
    # Lease expiration duration in seconds, server removes client if no heartbeat received within 10 seconds
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# knife4j 配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: org.example.serviceconsumer

knife4j:
  enable: true
  setting:
    language: zh_cn
